// Chatbot Application/src/components/ChatMessage.tsx
import { Avatar, AvatarFallback } from "./ui/avatar";
import { Bot, User } from "lucide-react";

interface ChatMessageProps {
  message: string;
  isUser: boolean;
  timestamp: Date;
}

export function ChatMessage({ message, isUser, timestamp }: ChatMessageProps) {
  return (
    <div className={`flex gap-3 ${isUser ? 'justify-end' : 'justify-start'} mb-4`}>
      {!isUser && (
        <Avatar className="h-8 w-8 mt-1">
          <AvatarFallback className="bg-primary text-primary-foreground">
            <Bot className="h-4 w-4" />
          </AvatarFallback>
        </Avatar>
      )}
      
      <div className={`flex flex-col max-w-[70%] ${isUser ? 'items-end' : 'items-start'}`}>
        <div
          className={`px-4 py-2 rounded-2xl ${
            isUser
              ? 'bg-primary text-primary-foreground'
              : 'bg-muted text-muted-foreground'
          }`}
        >
          <p className="break-words">{message}</p>
        </div>
        <span className="text-xs text-muted-foreground mt-1 px-2">
          {timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>

      {isUser && (
        <Avatar className="h-8 w-8 mt-1">
          <AvatarFallback className="bg-secondary text-secondary-foreground">
            <User className="h-4 w-4" />
          </AvatarFallback>
        </Avatar>
      )}
    </div>
  );
}

// frogdiskonto_frontend/src/components/ChatMessage.vue
<template>
  <div :class="['flex gap-3', isUser ? 'justify-end' : 'justify-start', 'mb-4']">
    <template v-if="!isUser">
        <div class="bg-primary text-primary-foreground h-8 w-8 mt-1 flex items-center justify-center">
            <i class="h-4 w-4 fas fa-robot"></i>
        </div>
    </template>

    <div :class="['flex flex-col max-w-[70%]', isUser ? 'items-end' : 'items-start']">
      <div :class="['px-4 py-2 rounded-2xl', isUser ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground']">
        <p class="break-words">{{ message }}</p>
      </div>
      <span class="text-xs text-muted-foreground mt-1 px-2">
        {{ formatTimestamp(timestamp) }}
      </span>
    </div>

    <template v-if="isUser">
  <div class="bg-secondary text-secondary-foreground h-8 w-8 mt-1 flex items-center justify-center">
    <i class="h-4 w-4 fa-regular fa-user"></i>
  </div>
</template>

  </div>
</template>

<script>

export default {
  name: 'ChatMessage',
  props: {
    message: {
      type: String,
      required: true,
    },
    isUser: {
      type: Boolean,
      required: true,
    },
    timestamp: {
      type: Date,
      required: true,
    },
  },
  methods: {
    formatTimestamp(timestamp) {
      return timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    },
  },
};
</script>
