// frogdiskonto_frontend/src/components/ChatInput.vue
<template>
  <form @submit.prevent="handleSubmit" class="flex gap-2 p-4 border-t bg-card">
    <input
      v-model="message"
      @keypress="handleKeyPress"
      placeholder="Type your message..."
      :disabled="disabled"
      class="flex-1"
    />
    <button :disabled="!message.trim() || disabled">Send</button>
  </form>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'ChatInput',
  props: {
    onSendMessage: {
      type: Function,
      required: true,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const message = ref('');

    const handleSubmit = () => {
      if (message.value.trim() && !props.disabled) {
        props.onSendMessage(message.value.trim());
        message.value = '';
      }
    };

    const handleKeyPress = (e) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        handleSubmit();
      }
    };

    return {
      message,
      handleSubmit,
      handleKeyPress,
    };
  },
};
</script>

// Chatbot Application (1)/src/components/ChatInput.tsx
import { useState } from "react";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { SendIcon } from "../icons/SendIcon";

interface ChatInputProps {
  onSendMessage: (message: string) => void;
  disabled?: boolean;
}

export function ChatInput({ onSendMessage, disabled }: ChatInputProps) {
  const [message, setMessage] = useState("");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (message.trim() && !disabled) {
      onSendMessage(message.trim());
      setMessage("");
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="flex gap-2 p-4 border-t bg-card">
      <Input
        value={message}
        onChange={(e) => setMessage(e.target.value)}
        onKeyPress={handleKeyPress}
        placeholder="Schreibe deine Nachricht..."
        disabled={disabled}
        className="flex-1"
      />
      <Button 
        type="submit" 
        disabled={!message.trim() || disabled}
        size="icon"
      >
        <SendIcon className="h-4 w-4" />
      </Button>
    </form>
  );
}
