// frogdiskonto_frontend/src/imports/Rectangle1.vue
<template>
  <div class="size-full flex justify-end items-center">
    <img :src="logo" alt="PostFinance SpendCast Microphone" class="h-full object-contain" />
  </div>
</template>

<script>
import logo from '../assets/pf_logo.png';

export default {
  name: 'Rectangle1',
  data() {
    return {
    logo
    };
  },
};
</script>

<style scoped>
/* Add any additional styles here if needed */
</style>

// Chatbot Application/src/imports/Rectangle1.tsx
import microphoneIcon from 'figma:asset/599c9c136cba84a047e74782d802f6b7c4ba9549.png';

export default function Rectangle1() {
  return (
    <div className="size-full flex justify-end items-center">
      <img src={microphoneIcon} alt="PostFinance SpendCast Microphone" className="h-full object-contain" />
    </div>
  );
}
